node('master'){
    
    def build_num = currentBuild.number
    def jenkinsNameJob = "Instalador"

    stage('cleaning'){
        deleteDir()
    }
    
    stage('Fetch') {
        timeout(time: 60, unit: 'SECONDS') {
            checkout scm
        }
    }
    
    stage('Hello world'){
        echo "opa, joia?"
    }
    
    stage('iterate over something'){
        dir('ci/'){
            def result = []
            def wrap = findFiles(glob: '*')
            wrap.each { it, i // iterator, index
            def full_path = it.getPath()
            result.add(full_path)
            }
            
        }
    }
}