node('master'){
    
    def build_num = currentBuild.number
    def jenkinsNameJob = "Instalador"
    
    stage('Fetch') {
        timeout(time: 60, unit: 'SECONDS') {
            checkout scm
        }
    }
    
    stage('Hello world'){
        echo "opa, joia?"
    }
    
    stage('iterate over something'){
        dir('docs/'){
            def files = findFiles(glob: 'ci/*-values.yaml')
            for (file in files){
                echo "${file[0].name}"
                
                
            }
        }
    }
}