node('master'){
    
    def build_num = currentBuild.number
    def jenkinsNameJob = "Instalador"

    stage('cleaning'){
        deleteDir()
    }
    
    stage('Fetch') {
        timeout(time: 60, unit: 'SECONDS') {
            checkout scm
        }
    }
    
    stage('Hello world'){
        echo "opa, joia?"
    }
    
    stage('iterate over something'){
        dir('ci/'){
            def nameWithoutExt = ''
            def files = findFiles(glob: '*.yaml')
            
            for(def file : files){
                nameWithoutExt = echo "$(basename "${file}")"

                echo "${nameWithoutExt}"

            }
        }
    }
}