name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branchname
      
      - name: Check branch name
        shell: bash
        run: echo "image:${{steps.extract_branchname.outputs.branch}}"

          
      - name: Git Clone
        run: |
          echo Create temporary folder to clone the repo into...
          TEMP_FOLDER="$(mktemp -d)" 
          echo Clone the repository...
          git clone "https://NCScorp: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@github.com/Nasajon/DevOps.git" ${TEMP_FOLDER}
          ls ${TEMP_FOLDER}/Ansible/roles/
        
      
